<?php

/**
 * @file hosting_sync.module
 *
 * Provides the front-end for syncing Aegir sites.
 */

include_once('hosting_sync.tasks.inc');

/**
 * Implementation of hook_perm()
 *
 * Since we have a node type, "create project content permission is
 * automatically added by Drupal
 */
function hosting_sync_perm() {
  return array(
    'create sync task',
  );
}

/**
 * Access Callback for Aegir Tasks
 *
 * This function defines access to the various aegir tasks.
 *
 * @arg $node object
 *   The node object is running the task. (Site, Platform, Server)
 *
 * @arg $task string
 *   The type of the task that is running.
 *
 * @see hosting_task_menu_access()
 *
 */
function hosting_sync_hosting_task_menu_access($node, $task) {
  // If we are passed the nid by mistake
  if (!isset($node->nid)){
    $node = node_load($node);
  }

  if ($task != 'delete' && !$node->status) {
    return FALSE;
  }

  return user_access("create " . $task . " task");
}

