<?php

/**
 * Implementation of hook_hosting_tasks
 */
function hosting_tasks_extra_hosting_tasks() {
  $nid = menu_get_object();
  $site = node_load($nid->nid);
  $tasks = array();

  $tasks['site']['flush_cache'] = array(
    'title' => t('Flush all caches'),
    'description' => t('Flushes all caches.'),
  );
  $tasks['site']['rebuild_registry'] = array(
    'title' => t('Rebuild registry'),
    'description' => t('Rebuilds the registry and flushes all caches.'),
  );
  $tasks['site']['run_cron'] = array(
    'title' => t('Run standard cron'),
    'description' => t('Runs standard cron.'),
  );
  $tasks['site']['delete_rebuild_registry'] = array(
    'title' => t('Delete & rebuild D7 registry'),
    'description' => t('Truncates and re-creates registry tables.'),
  );

  return $tasks;
}

/**
 * Implementation of hook_perm()
 */
function hosting_tasks_extra_perm() {
  return array(
    'create rebuild_registry task',
    'create flush_cache task',
    'create run_cron task',
    'create delete_rebuild_registry task',
  );
}
